Repository boostcampwm-2024/and06-musicroad, pull requests merged in 2024-12, with the labels that each got.

#130 [design] 유저 정보 화면 UI
  app/src/main/java/com/squirtles/musicroad/common/Constants.kt
  app/src/main/java/com/squirtles/musicroad/common/Spacer.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickScreen.kt
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
  app/src/main/java/com/squirtles/musicroad/favorite/FavoriteScreen.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/Destinations.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavigationActions.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/components/BottomNavigation.kt
  app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
  app/src/main/java/com/squirtles/musicroad/map/components/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/DeletePickDialog.kt
  app/src/main/java/com/squirtles/musicroad/userinfo/MenuItem.kt
  app/src/main/java/com/squirtles/musicroad/userinfo/UserInfoMenus.kt
  app/src/main/java/com/squirtles/musicroad/userinfo/UserInfoScreen.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerOverlay.kt
  app/src/main/res/drawable/img_user_default_profile.jpg
  app/src/main/res/values/strings.xml
Labels: design

#132 [feature] 뮤직비디오 화면 UI 개선
  app/build.gradle.kts
  app/src/main/java/com/squirtles/musicroad/common/AlbumImage.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/CommentText.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/MusicVideoKnob.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/MusicVideoPlayer.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/MusicVideoScreen.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerOverlay.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerViewModel.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/model/FirebasePick.kt
  data/src/main/java/com/squirtles/data/mapper/AppleMusicMapper.kt
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  domain/src/main/java/com/squirtles/domain/model/MusicVideo.kt
  domain/src/main/java/com/squirtles/domain/model/Pick.kt
  domain/src/main/java/com/squirtles/domain/usecase/music/FetchMusicVideoUseCase.kt
  gradle/libs.versions.toml
Labels: design, feature

#133 [refactor] 픽 보관함/등록한 픽 목록을 보여주는 순서 설정
  app/src/main/java/com/squirtles/musicroad/common/PickInfoText.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickItem.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListScreen.kt
  app/src/main/java/com/squirtles/musicroad/userinfo/UserInfoMenus.kt
  app/src/main/java/com/squirtles/musicroad/userinfo/UserInfoScreen.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
Labels: refactor

#138 [feature] 음악 검색 결과를 페이징으로 보여주기
  app/build.gradle.kts
  app/src/main/java/com/squirtles/musicroad/create/CreatePickUiState.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/AppleMusicDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/SearchSongsPagingSource.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/api/AppleMusicApi.kt
  data/src/main/java/com/squirtles/data/repository/AppleMusicRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/squirtles/domain/datasource/AppleMusicRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/repository/AppleMusicRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/music/SearchSongsUseCase.kt
  gradle/libs.versions.toml
Labels: feature

#139 [feature] 현재 위치 로딩 다이얼로그 및 권한 요청 방식 수정
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/main/MainViewModel.kt
  app/src/main/java/com/squirtles/musicroad/main/NeedPermissionDialog.kt
  app/src/main/java/com/squirtles/musicroad/main/PermissionSnackbar.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
  app/src/main/java/com/squirtles/musicroad/map/components/LoadingDialog.kt
  app/src/main/res/values/strings.xml
Labels: refactor

#140 [hotfix] 픽 클릭 시 흰화면이 자주 뜨는 문제 해결
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/CommentText.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
Labels: bug

#141 [hotfix] 원형 재생바 터치 영역 수정
  app/src/main/java/com/squirtles/musicroad/pick/components/PlayCircularProgressIndicator.kt
Labels: refactor

#142 [feature] QA 피드백 반영 및 플레이어 디자인 변경
  app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/CommentText.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/MusicPlayer.kt
  app/src/main/java/com/squirtles/musicroad/ui/theme/Color.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/MusicVideoScreen.kt
  app/src/main/res/values/strings.xml
Labels: design, feature

#149 [fix] 오디오 비주얼라이저가 노래 정보를 가리지 않도록 수정
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/SongInfo.kt
Labels: bug

#150 [ fix] 앱 이름 설정
  app/src/main/AndroidManifest.xml
Labels: bug

#144 [feature] 픽 담기 부분 보완
  app/src/main/java/com/squirtles/musicroad/common/ThrottleFirst.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
Labels: refactor

#146 [fix] 다른 화면으로 전환 후 돌아오면 스낵바가 보이지 않는 문제 해결
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/main/PermissionBar.kt
  app/src/main/java/com/squirtles/musicroad/main/PermissionSnackbar.kt
  app/src/main/java/com/squirtles/musicroad/ui/theme/Theme.kt
Labels: design

#151 [feature] 픽 삭제 시 담은 픽과 유저 정보 관리 DB에서도 삭제
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/FirebaseRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/mypick/DeletePickUseCase.kt
Labels: firebase

#152 [feature] 지도의 카메라 영역 제한
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
Labels: bug

#153 [refactor] 클릭한 마커가 위에 오도록
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
  app/src/main/java/com/squirtles/musicroad/map/marker/Clusterer.kt
Labels: refactor

#147 [feature] 내 프로필과 다른 사람 프로필 구현, 닉네임 수정 기능 구현
  app/src/main/java/com/squirtles/musicroad/common/CreatedByPickText.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/Destinations.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavigationActions.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/DetailPickTopAppBar.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListScreen.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListViewModel.kt
  app/src/main/java/com/squirtles/musicroad/profile/MenuItem.kt
  app/src/main/java/com/squirtles/musicroad/profile/ProfileMenus.kt
  app/src/main/java/com/squirtles/musicroad/profile/ProfileScreen.kt
  app/src/main/java/com/squirtles/musicroad/profile/ProfileViewModel.kt
  app/src/main/java/com/squirtles/musicroad/setting/SettingNotificationScreen.kt
  app/src/main/java/com/squirtles/musicroad/setting/SettingProfileScreen.kt
  app/src/main/java/com/squirtles/musicroad/setting/SettingScreen.kt
  app/src/main/java/com/squirtles/musicroad/userinfo/UserInfoScreen.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Attributes.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/mapper/AppleMusicMapper.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/FirebaseRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/user/FetchUserByIdUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/user/UpdateUserNameUserCase.kt
Labels: feature, firebase

#154 [feature] 오버레이가 기기의 카메라에 가려지지 않도록 수정
  app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerOverlay.kt
Labels: design

#155 [refactor] 검색 결과 클릭하여 화면 전환 시 키보드 내리기
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
Labels: refactor

#157 [feature] 영상 비율 개선
  app/src/main/java/com/squirtles/musicroad/videoplayer/MusicVideoPlayer.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerViewModel.kt
Labels: refactor

#160 [feature] 픽 목록 정렬 기준 추가
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/picklist/OrderBottomSheet.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListScreen.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListType.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListUiState.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListViewModel.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/datasource/local/LocalDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/repository/LocalRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/LocalDataSource.kt
  domain/src/main/java/com/squirtles/domain/model/Order.kt
  domain/src/main/java/com/squirtles/domain/repository/LocalRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/local/GetFavoriteListOrderUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/local/GetMyListOrderUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/local/SaveFavoriteListOrderUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/local/SaveMyListOrderUseCase.kt
Labels: feature
