Repository boostcampwm-2024/and06-musicroad, pull requests merged in 2024-11, with the labels that each got.

#68 [feature] 프로젝트에 Firebase 추가
  .gitignore
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: firebase

#69 [feature] 네이버맵 API 키설정 및 의존성 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: chore

#70 [layout] 테마 색상 설정
  app/src/main/java/com/squirtles/musicroad/ui/theme/Color.kt
  app/src/main/java/com/squirtles/musicroad/ui/theme/Theme.kt
Labels: layout

#72 [feature] MainActivity 지도 띄우기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/squirtles/musicroad/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/map/MapFragment.kt
  app/src/main/res/layout/fragment_map.xml
  gradle/libs.versions.toml
Labels: layout, feature

#75 [feature] Compose Navigation 설정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/squirtles/musicroad/favorite/FavoriteScreen.kt
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavigation.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  gradle/libs.versions.toml
Labels: feature

#76 [feature] 지도에 내 위치와 반경 표시하기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/map/MapFragment.kt
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#77 [feature] 바텀 내비게이션 버튼
  app/src/main/java/com/squirtles/musicroad/favorite/FavoriteScreen.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavigation.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/setting/SettingScreen.kt
  app/src/main/java/com/squirtles/musicroad/ui/theme/Theme.kt
  app/src/main/res/drawable/ic_musical_note_64.png
  app/src/main/res/values/strings.xml
Labels: design

#78 [feature] 스포티파이 검색 요청 데이터 정의 및 테스트
  data/src/main/java/com/squirtles/data/datasource/remote/api/SpotifyApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/api/TokenApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/AccessTokenResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/Album.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/Artist.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/ExternalUrls.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/Image.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/SpotifyResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/Track.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/Tracks.kt
  data/src/main/java/com/squirtles/data/di/ApiModule.kt
Labels: feature, firebase

#80 [feature] 앱 아이콘 설정
  app/src/main/AndroidManifest.xml
  app/src/main/ic_musicroad-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_musicroad.xml
  app/src/main/res/mipmap-anydpi-v26/ic_musicroad_round.xml
  app/src/main/res/mipmap-hdpi/ic_musicroad.webp
  app/src/main/res/mipmap-hdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_musicroad_round.webp
  app/src/main/res/mipmap-mdpi/ic_musicroad.webp
  app/src/main/res/mipmap-mdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_musicroad_round.webp
  app/src/main/res/mipmap-xhdpi/ic_musicroad.webp
  app/src/main/res/mipmap-xhdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_musicroad_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_musicroad.webp
  app/src/main/res/mipmap-xxhdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_musicroad_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_musicroad.webp
  app/src/main/res/mipmap-xxxhdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_musicroad_round.webp
  app/src/main/res/values/ic_musicroad_background.xml
Labels: design

#81 [feature] 인포윈도우 컴포넌트 생성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/squirtles/musicroad/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/map/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/map/MapFragment.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/ui/theme/Theme.kt
  app/src/main/res/drawable/ic_favorite.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/squirtles/data/datasource/remote/FirebaseDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/TempRemoteDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/api/SpotifyApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/api/TempApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/api/TokenApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/firebase/FirebasePick.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/AccessTokenResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Album.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Artist.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/ExternalUrls.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Image.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/SpotifyResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/TempResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Track.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Tracks.kt
  data/src/main/java/com/squirtles/data/di/DataModule.kt
  data/src/main/java/com/squirtles/data/di/FirebaseModule.kt
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  data/src/main/java/com/squirtles/data/mapper/Mapper.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryException.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/FirebaseRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/model/Pick.kt
  domain/src/main/java/com/squirtles/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/FetchPickInAreaUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/FetchPickUseCase.kt
  gradle/libs.versions.toml
Labels: design

#86 [feature] 앱 아이콘 개선 및 스플래시 화면 띄우기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_musicroad-playstore.png
  app/src/main/ic_musicroad_playstore.png
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_musicroad_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_musicroad.xml
  app/src/main/res/mipmap-anydpi-v26/ic_musicroad_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-hdpi/ic_musicroad.webp
  app/src/main/res/mipmap-hdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_musicroad_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_musicroad.webp
  app/src/main/res/mipmap-mdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_musicroad_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_musicroad.webp
  app/src/main/res/mipmap-xhdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_musicroad_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_musicroad.webp
  app/src/main/res/mipmap-xxhdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_musicroad_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_musicroad.webp
  app/src/main/res/mipmap-xxxhdpi/ic_musicroad_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_musicroad_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_musicroad_background.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: design

#93 [feature] 애플뮤직 API 검색 받아오기, 검색화면 UI 및 검색 테스트
  app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavigation.kt
  app/src/main/java/com/squirtles/musicroad/map/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/search/SearchMusicScreen.kt
  app/src/main/java/com/squirtles/musicroad/search/SearchViewModel.kt
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/squirtles/data/datasource/remote/api/SpotifyApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/api/TokenApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/AppleMusicDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/api/AppleMusicApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Artwork.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Attributes.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Data.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/MusicVideoResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Preview.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Results.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/SearchResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Songs.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/model/FirebasePick.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/AccessTokenResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Album.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Artist.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/ExternalUrls.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Image.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/SpotifyResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/TempResponse.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Track.kt
  data/src/main/java/com/squirtles/data/datasource/remote/model/spotify/Tracks.kt
  data/src/main/java/com/squirtles/data/di/ApiModule.kt
  data/src/main/java/com/squirtles/data/di/DataModule.kt
  data/src/main/java/com/squirtles/data/exception/AppleMusicException.kt
  data/src/main/java/com/squirtles/data/exception/FirebaseException.kt
  data/src/main/java/com/squirtles/data/mapper/AppleMusicMapper.kt
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  data/src/main/java/com/squirtles/data/repository/AppleMusicRepositoryImpl.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/AppleMusicRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/model/MusicVideo.kt
  domain/src/main/java/com/squirtles/domain/model/Pick.kt
  domain/src/main/java/com/squirtles/domain/model/Song.kt
  domain/src/main/java/com/squirtles/domain/repository/AppleMusicRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/SearchMusicVideoUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/SearchSongsUseCase.kt
Labels: design, feature, firebase

#94 [feature] 픽 등록화면 UI
  app/src/main/java/com/squirtles/musicroad/map/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/pick/CreatePickScreen.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/mapper/AppleMusicMapper.kt
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  domain/src/main/java/com/squirtles/domain/model/Song.kt
Labels: design

#95 [feature] 음악 검색 결과 표시
  app/src/main/java/com/squirtles/musicroad/search/SearchMusicScreen.kt
  data/src/main/java/com/squirtles/data/mapper/AppleMusicMapper.kt
  domain/src/main/java/com/squirtles/domain/model/Song.kt
  gradle/libs.versions.toml
Labels: feature

#96 [feature] 픽 정보 화면 구현
  app/src/main/java/com/squirtles/musicroad/map/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_favorite_false.xml
  app/src/main/res/drawable/ic_favorite_true.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  domain/src/main/java/com/squirtles/domain/model/Pick.kt
Labels: design, feature, firebase

#98 [feature] 알림 반경 내 픽 개수 불러오기
  app/src/main/java/com/squirtles/musicroad/map/MapFragment.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/res/values/strings.xml
Labels: design, feature

#99 [feature] 검색-등록 화면이동, Firestore에 픽정보 등록
  app/src/main/java/com/squirtles/musicroad/create/CreatePickScreen.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
  app/src/main/java/com/squirtles/musicroad/main/Destinations.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavigationActions.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMapFragment.kt
  app/src/main/java/com/squirtles/musicroad/pick/CreatePickScreen.kt
  app/src/main/java/com/squirtles/musicroad/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_map.xml
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/AppleMusicDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/model/FirebasePick.kt
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/FirebaseRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/CreatePickUseCase.kt
Labels: feature, firebase

#106 [ feature] MapFragment 제거 후 MapScreen에서 지도 기능 통합
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMapFragment.kt
  app/src/main/res/layout/fragment_map.xml
Labels: refactor

#107 [feature] SearchTopBar 텍스트 포커스 문제해결, 키보드 검색 버튼
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
Labels: refactor

#101 [feature] 마커 클릭 시 인포윈도우 표시 및 인포윈도우 클릭 시 상세 정보 화면으로 이동
  app/src/main/java/com/squirtles/musicroad/main/Destinations.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavigationActions.kt
  app/src/main/java/com/squirtles/musicroad/map/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/map/MarkerIconView.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
Labels: feature

#109 [feature] 현재 위치 저장 및 공유 위한 데이터 레이어 구현
  app/src/main/java/com/squirtles/musicroad/create/CreatePickScreen.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/map/BottomNavigation.kt
  app/src/main/java/com/squirtles/musicroad/map/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/map/MarkerIconView.kt
  app/src/main/java/com/squirtles/musicroad/map/MusicRoadMarker.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  data/src/main/java/com/squirtles/data/datasource/local/LocalDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/di/DataModule.kt
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  data/src/main/java/com/squirtles/data/repository/LocalRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/LocalDataSource.kt
  domain/src/main/java/com/squirtles/domain/model/Pick.kt
  domain/src/main/java/com/squirtles/domain/repository/LocalRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/FetchLastLocationUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/SaveLastLocationUseCase.kt
Labels: refactor, feature

#112 [feature] 뮤직비디오 정보 저장하기
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/AppleMusicDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/api/AppleMusicApi.kt
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Artwork.kt
  data/src/main/java/com/squirtles/data/di/ApiModule.kt
  data/src/main/java/com/squirtles/data/repository/AppleMusicRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/AppleMusicRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/repository/AppleMusicRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/GetMusicVideoUrlUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/SearchMusicVideoUseCase.kt
Labels: feature

#111 [feature] 지도 화면 영역에 존재하는 픽 정보 마커 표시
  app/src/main/java/com/squirtles/musicroad/map/BottomNavigation.kt
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
Labels: feature

#113 [feature] Swipe 제스처로 뮤직비디오 화면으로 전환
  app/build.gradle.kts
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/MusicVideoScreen.kt
  app/src/main/res/drawable/ic_swipe.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  gradle/libs.versions.toml
Labels: design, feature

#115 [feature] 음악 검색 결과 자동으로 표시
  app/src/main/java/com/squirtles/musicroad/UiState.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
Labels: refactor, feature

#117 [feature] 음원재생 UI, ExoPlayer 이용 음원재생 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/Destinations.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavigationActions.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/map/MusicRoadMarker.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
  app/src/main/java/com/squirtles/musicroad/map/components/BottomNavigation.kt
  app/src/main/java/com/squirtles/musicroad/map/components/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/map/components/MarkerIconView.kt
  app/src/main/java/com/squirtles/musicroad/map/components/PickNotificationBanner.kt
  app/src/main/java/com/squirtles/musicroad/musicplayer/PlayerState.kt
  app/src/main/java/com/squirtles/musicroad/musicplayer/PlayerViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/CommentText.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/PickInformation.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/SongInfo.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/SwipeUpIcon.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/MusicPlayer.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/PlayBar.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/PlayProgressIndicator.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/PlayerControls.kt
  app/src/main/java/com/squirtles/musicroad/ui/theme/Color.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/di/FirebaseModule.kt
  gradle/libs.versions.toml
Labels: design, feature

#119 [feature] 유저 정보 저장 및 불러오기
  app/src/main/java/com/squirtles/musicroad/create/CreatePickScreen.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/main/MainViewModel.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/map/components/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/SongInfo.kt
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/squirtles/data/datasource/local/LocalDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/model/FirebasePick.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/model/FirebaseUser.kt
  data/src/main/java/com/squirtles/data/di/DataModule.kt
  data/src/main/java/com/squirtles/data/exception/FirebaseException.kt
  data/src/main/java/com/squirtles/data/mapper/FirebaseMapper.kt
  data/src/main/java/com/squirtles/data/repository/AppleMusicRepositoryImpl.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryImpl.kt
  data/src/main/java/com/squirtles/data/repository/LocalRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/FirebaseRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/datasource/LocalDataSource.kt
  domain/src/main/java/com/squirtles/domain/exception/AppleMusicException.kt
  domain/src/main/java/com/squirtles/domain/exception/FirebaseException.kt
  domain/src/main/java/com/squirtles/domain/model/Pick.kt
  domain/src/main/java/com/squirtles/domain/model/Temp.kt
  domain/src/main/java/com/squirtles/domain/model/User.kt
  domain/src/main/java/com/squirtles/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/squirtles/domain/repository/LocalRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/CreateUserUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/FetchUserUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/GetCurrentUserUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/GetUserIdFromLocalStorageUseCase.kt
  gradle/libs.versions.toml
Labels: feature, firebase

#120 [feature] 마커 클러스터링
  app/src/main/java/com/squirtles/musicroad/common/AlbumImage.kt
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/map/MusicRoadMarker.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
  app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
  app/src/main/java/com/squirtles/musicroad/map/components/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/map/components/Text.kt
  app/src/main/java/com/squirtles/musicroad/map/marker/ClusterMarkerIconView.kt
  app/src/main/java/com/squirtles/musicroad/map/marker/Clusterer.kt
  app/src/main/java/com/squirtles/musicroad/map/marker/DensityType.kt
  app/src/main/java/com/squirtles/musicroad/map/marker/LeafMarkerIconView.kt
  app/src/main/java/com/squirtles/musicroad/map/marker/MarkerKey.kt
  app/src/main/java/com/squirtles/musicroad/ui/theme/Color.kt
  app/src/main/java/com/squirtles/musicroad/ui/theme/Theme.kt
  app/src/main/res/values/strings.xml
Labels: feature

#124 [feature] 내가 등록한 픽 삭제 및 일부 화면 UiState 적용
  app/src/main/java/com/squirtles/musicroad/UiState.kt
  app/src/main/java/com/squirtles/musicroad/common/CreatedByPickText.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickScreen.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickUiState.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
  app/src/main/java/com/squirtles/musicroad/map/components/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/map/components/Text.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickUiState.kt
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/DeletePickDialog.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/DetailPickTopAppBar.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/squirtles/data/datasource/remote/applemusic/AppleMusicDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/FirebaseRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/DeletePickUseCase.kt
Labels: refactor, feature

#122 [feature] 오디오 시각화, 원형 재생바
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/squirtles/musicroad/main/MainActivity.kt
  app/src/main/java/com/squirtles/musicroad/musicplayer/PlayerViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/CircleAlbumCover.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/PlayCircularProgressIndicator.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/MusicPlayer.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/visualizer/BaseVisualizer.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/visualizer/CanvasCircleVisualizer.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/music/visualizer/CircleVisualizer.kt
  app/src/main/res/values/strings.xml
Labels: design, feature

#126 [feature] 지도 다크모드
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
Labels: design

#125 [feature] 뮤직비디오 오버레이 화면 및 컨트롤러 구현
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/MusicVideoPlayer.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/MusicVideoScreen.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerOverlay.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerState.kt
  app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerViewModel.kt
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/squirtles/domain/usecase/GetMusicVideoUrlUseCase.kt
Labels: design, feature

#127 [hotfix] 비주얼라이저 캡처 버그 해결
  app/src/main/java/com/squirtles/musicroad/musicplayer/PlayerViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/CircleAlbumCover.kt
Labels: feature

#128 [feature] 픽 담기 및 해제, 픽 보관함
  app/src/main/java/com/squirtles/musicroad/UiState.kt
  app/src/main/java/com/squirtles/musicroad/common/AlbumImage.kt
  app/src/main/java/com/squirtles/musicroad/common/Constants.kt
  app/src/main/java/com/squirtles/musicroad/common/DefaultTopAppBar.kt
  app/src/main/java/com/squirtles/musicroad/common/PickInfoText.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickScreen.kt
  app/src/main/java/com/squirtles/musicroad/create/CreatePickUiState.kt
  app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
  app/src/main/java/com/squirtles/musicroad/favorite/FavoriteScreen.kt
  app/src/main/java/com/squirtles/musicroad/favorite/FavoriteViewModel.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavGraph.kt
  app/src/main/java/com/squirtles/musicroad/main/navigations/MainNavigationActions.kt
  app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
  app/src/main/java/com/squirtles/musicroad/map/components/InfoWindowCard.kt
  app/src/main/java/com/squirtles/musicroad/map/components/Text.kt
  app/src/main/java/com/squirtles/musicroad/map/marker/LeafMarkerIconView.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickUiState.kt
  app/src/main/java/com/squirtles/musicroad/pick/PickViewModel.kt
  app/src/main/java/com/squirtles/musicroad/pick/components/DetailPickTopAppBar.kt
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/CloudFunctionHelper.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
  data/src/main/java/com/squirtles/data/datasource/remote/firebase/model/FirebaseFavorite.kt
  data/src/main/java/com/squirtles/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/java/com/squirtles/domain/datasource/FirebaseRemoteDataSource.kt
  domain/src/main/java/com/squirtles/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/squirtles/domain/usecase/CreateFavoriteUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/DeleteFavoriteUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/FetchIsFavoriteUseCase.kt
  domain/src/main/java/com/squirtles/domain/usecase/GetFavoritePicksUseCase.kt
  gradle/libs.versions.toml
Labels: design, feature, firebase
