Repository boostcampwm-2024/and06-musicroad, pull requests merged in 2025-01, with the labels that each got.

#164 [feature] firebase crashlytics 설정
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: chore, firebase

#161 [feature] 픽 목록 편집 모드
  app/src/main/java/com/squirtles/musicroad/common/DefaultTopAppBar.kt
  app/src/main/java/com/squirtles/musicroad/common/MessageAlertDialog.kt
  app/src/main/java/com/squirtles/musicroad/common/PickInfoText.kt
  app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
  app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
  app/src/main/java/com/squirtles/musicroad/picklist/DeleteSelectedPickDialog.kt
  app/src/main/java/com/squirtles/musicroad/picklist/EditModeAction.kt
  app/src/main/java/com/squirtles/musicroad/picklist/EditModeBottomButton.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickItem.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListScreen.kt
  app/src/main/java/com/squirtles/musicroad/picklist/PickListViewModel.kt
  app/src/main/res/values/strings.xml
Labels: refactor, feature

#166 [refactor] 지도 화면 영역의 픽 목록을 가져오는 시점 변경
  app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
  app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
Labels: refactor
